# Generated by Django 4.1.4 on 2022-12-15 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("stockmgt", "0002_remove_stock_export_to_csv_alter_stock_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
